# Use postgres/example user/password credentials
version: '3.1'

services:

  app:
    image: service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    ports: 
      - ${PORT}:${PORT}

  # db:
  #   image: postgres:alpine3.18
  #   restart: always
    # environment:
    #   POSTGRES_PASSWORD: example
